In [1]:
# Importing Libraries
from tqdm.notebook import trange, tqdm
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [2]:
#Inspect the data frame
#Index on the left does not have a name and everything is off to the right.
df.sample(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
431969,Data Scientist,Chief Data Science and Data Engineering Office...,"Charleroi, Belgium",via BeBee Belgique,Part-time,False,Belgium,2023-06-15 16:55:28,False,False,Belgium,None,NaN,NaN,EliteRecruitmentGroup,['aws'],{'cloud': ['aws']}
774096,Senior Data Engineer,Senior Data Engineer,"Sydney NSW, Australia",via BeBee Australia,Full-time,False,Australia,2023-08-18 01:12:28,True,False,Australia,None,NaN,NaN,Paxus,"['sql', 'snowflake', 'flow', 'git']","{'cloud': ['snowflake'], 'other': ['flow', 'gi..."
467204,Data Engineer,Data Engineer,"Dallas, TX",via Dice,Contractor,False,Sudan,2023-11-21 15:43:24,False,False,Sudan,None,NaN,NaN,Raas Infotek LLC,"['python', 'java', 'scala', 'aws', 'spark', 'k...","{'cloud': ['aws'], 'libraries': ['spark', 'kaf..."
664024,Data Analyst,Data Analytics Apprenticeship (Undergraduate),"Dallas, TX",via ZipRecruiter,Full-time,False,"Texas, United States",2023-05-02 10:02:36,False,False,United States,None,NaN,NaN,Lockton Companies,"['sas', 'sas', 'r', 'python', 'tableau', 'exce...","{'analyst_tools': ['sas', 'tableau', 'excel', ..."
421136,Business Analyst,Strategy and Performance Analyst (m/f/d),Anywhere,via LinkedIn Luxembourg,Full-time,True,Luxembourg,2023-02-28 17:02:59,False,False,Luxembourg,None,NaN,NaN,bp,['excel'],{'analyst_tools': ['excel']}

In [3]:
#Check the index
df.index

RangeIndex(start=0, stop=785741, step=1)

In [4]:
#Check the name of the index and name it
df.index.name = "job_index"

In [5]:
#Check if the name saved
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [6]:
#Attritubes data type
df.index.dtype

dtype('int64')

In [7]:
#Reset_index()
#Filtering the df for USA jobs

df_usa = df[df['job_country']== 'United States']

In [8]:
df_usa.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."